# Generated by Django 5.2.3 on 2025-07-04 01:14

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del producto', max_length=100, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(help_text='Descripción detallada del producto', verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='El precio debe ser mayor a 0')], verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, message='El stock no puede ser negativo')], verbose_name='Stock Disponible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoría')),
                ('codigo_producto', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de Producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['nombre'], name='productos_p_nombre_456643_idx'), models.Index(fields=['categoria'], name='productos_p_categor_15e07f_idx'), models.Index(fields=['activo'], name='productos_p_activo_31f808_idx')],
            },
        ),
    ]
